### ISSUE TITLE
Analise preliminar para conhecer os dados

### ISSUE THREAD

**Issue by RickyOliveira** [ICEI-PUC-Minas-PMV-SI/pmv-si-2024-2-pe7-t1-analise_diabetes#3]
> registro detalhado e descritivo e exploração da base de dados selecionada na Etapa 1

**Comment by Hiweus** [comment]
Usando o heatmap como ferramenta podemos ver a correlação entre os parâmetros
 
A classificação (presença ou ausência) de diabetes se correlaciona fortemente com:
- Polyuria: Presença de micção excessiva.
- Polydipsia: Sede excessiva
Além do fato que `Polyuria` e `Polydipsia` se correlacionam entre si.

O parâmetro de idade se correlaciona com todos os parâmetros do dataset.

![Image](https://github.com/user-attachments/assets/2b003015-b134-47d1-89ed-ea3a1bc34247)

**Comment by renatojuniorrs** [comment]
Analisar correlação multivalorada entre Obesidade e Diabetes

![Image](https://github.com/user-attachments/assets/423c2269-e176-4af2-9f8e-876260a1a05a)

- Foi observado que dentro do universo dos dados analisados, apenas 19.06% das pessoas que testaram positivo para diabetes apresentavam obesidade.

**Comment by renatojuniorrs** [comment]
Analisar correlação multivalorada entre Polidipsia e Diabetes

![Image](https://github.com/user-attachments/assets/b1608371-9804-4f69-971b-87d0795de231)

- Foi observado que dentro do universo dos dados analisados, 70.31% das pessoas que testaram positivo para diabetes apresentaram Polidipsia .

**Comment by renatojuniorrs** [comment]
Analisar correlação multivalorada entre Coceira e Diabetes

![Image](https://github.com/user-attachments/assets/d2217a27-9d4b-4b13-8ea2-192c60eb3a48)

- Foi observado que dentro do universo dos dados analisados, 48.13% das pessoas que testaram positivo para diabetes apresentaram coceira.

**Comment by renatojuniorrs** [comment]
Analisar correlação multivalorada entre Cicatrização Tardia e Diabetes

![Image](https://github.com/user-attachments/assets/4bd960a6-257f-452a-9d5f-ae019036049a)

- Foi observado que dentro do universo dos dados analisados, 47.81% das pessoas que testaram positivo para diabetes apresentaram  Cicatrização Tardia.

**Comment by renatojuniorrs** [comment]
Analisar correlação multivalorada entre Fraqueza e Diabetes

![Image](https://github.com/user-attachments/assets/5d80eb04-38ba-4f42-92ac-42c88ab03e98)

- Foi observado que dentro do universo dos dados analisados, 68.13% das pessoas que testaram positivo para diabetes apresentaram  Cicatrização Tardia.

**Comment by renatojuniorrs** [comment]
Analisar correlação multivalorada entre Perca de Peso Repentina e Diabetes

![Image](https://github.com/user-attachments/assets/d11f6fcc-d399-4b78-aec1-1e05c3926548)

- Foi observado que dentro do universo dos dados analisados, 58.75% das pessoas que testaram positivo para diabetes apresentaram  Perca de Peso Repentina.

**Comment by renatojuniorrs** [comment]
Analisar correlação multivalorada entre Visão Embaçada e Diabetes

![Image](https://github.com/user-attachments/assets/e875da58-3100-4e87-9c5e-9f4942f8632e)

- Foi observado que dentro do universo dos dados analisados, 54.69% das pessoas que testaram positivo para diabetes apresentaram  Visão Embaçada.

**Comment by renatojuniorrs** [comment]
- Analisar correlação entre Obesidade x Polidipsia e Diabetes

![Image](https://github.com/user-attachments/assets/37d745dd-e9c8-4681-8106-1edbbe4d3b0a)

- Foi observado que dentro do universo dos dados analisados, 57,50% das pessoas que testaram positivo para diabetes apresentavam concomitantemente Obesidade e Polidipsia.
- O Número total de pessoas que testaram positivo para diabetes e apresentavam concomitantemente Obesidade e Polidipsia é de 184 pessoas
- O Número total de pessoas com obesidade que fazem parte do universo analisado é de 320 pessoas

**Comment by renatojuniorrs** [comment]
Analisar correlação entre Idade e Diabetes
![Image](https://github.com/user-attachments/assets/c64e3068-caff-4d0a-a197-db108b0db2bc)
- No modelo de gráfico "Mapa de Árvore" não foi possível identificar com facilidade correlação entre a idade e diabetes.
- Destaca-se apenas que em um primeiro momento é possível observar que no universo analisado são menores os casos de incidência de diabetes em crianças e adolescentes
- Possivelmente, melhores correlações poderão ser encontrados realizando a distribuição das idades em intervalos

**Comment by renatojuniorrs** [comment]
Analisar correlação entre Intervalo de Idades e Diabetes

- Método da separação de Intervalo
![Image](https://github.com/user-attachments/assets/5cca2bcc-4ebb-40a4-8f1b-d4c1d6843dbf)

- Resultado
![Image](https://github.com/user-attachments/assets/745b0c0f-e7c0-4e7f-983c-ed3bf1a58929)

No modelo de gráfico "Mapa de Árvore" não foi possível identificar com facilidade correlação entre a idade e diabetes.
